# Inference Service Worker Configuration
# This worker is exposed via Service Bindings (not HTTP routes)

name = "inference-service"
main = "index.ts"
compatibility_date = "2024-10-01"
account_id = "d9700a3fcc05a01f5d81670ebbae817d"

# Workers AI binding
[ai]
binding = "AI"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "inference-ui-db"
database_id = "4de74839-04b8-4b83-8550-578701999006"

# R2 Storage binding
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "inference-ui-assets"

# KV Cache binding
[[kv_namespaces]]
binding = "KV"
id = "813d5ccd33b943439c91f52b5b682372"

# Analytics Engine binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# NOTE: This worker is NOT exposed via routes
# It is called directly by other workers via service bindings
# No routes = no HTTP access, only RPC calls
# Wrangler will handle TypeScript compilation automatically
