# Cloudflare Workers Configuration
# Account: FinHub

name = "inference-ui-api"
account_id = "d9700a3fcc05a01f5d81670ebbae817d"
main = "src/index.ts"
compatibility_date = "2024-10-01"
workers_dev = true

# Smart Placement - Automatically place worker near backend services
# Reduces latency by running worker close to D1, R2, KV, and service bindings
[placement]
mode = "smart"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "inference-ui-db"
database_id = "4de74839-04b8-4b83-8550-578701999006"

# R2 Storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "inference-ui-assets"

# KV Namespace
[[kv_namespaces]]
binding = "KV"
id = "813d5ccd33b943439c91f52b5b682372"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Workers AI - For AI inference
[ai]
binding = "AI"

# Service Bindings - Direct RPC to other workers (no HTTP overhead)
# This allows the main API worker to call the inference service directly
[[services]]
binding = "INFERENCE"
service = "inference-service"

# Environment Variables
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"

# Production Environment
[env.production]
name = "inference-ui-api-production"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"

# Durable Objects - Commented out until RealtimeSession is deployed
# [[durable_objects.bindings]]
# name = "REALTIME"
# class_name = "RealtimeSession"
# script_name = "inference-ui-realtime"

# Build Configuration
[build]
command = "npm run build"

# Triggers for scheduled events - Commented out for initial deployment
# [[triggers.crons]]
# cron = "0 * * * *" # Every hour
