# Cloudflare Workers Configuration
# Account: Neureus

name = "inference-ui-api"
account_id = "2bba1309281bf805590ca30d4e49adb0"
main = "src/index.ts"
compatibility_date = "2024-10-01"
workers_dev = true

# Smart Placement - Automatically place worker near backend services
# Reduces latency by running worker close to D1, R2, KV, and service bindings
[placement]
mode = "smart"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "inference-ui-db"
database_id = "47fd4ca8-72b1-44be-b310-53feb2e0a101"

# R2 Storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "inference-ui-assets"

# KV Namespace
[[kv_namespaces]]
binding = "KV"
id = "a9cf26e3f5104521b279b245adaa2801"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Service Bindings - Worker-to-Worker Communication
[[services]]
binding = "STREAMING"
service = "inference-ui-streaming"
environment = "production"

# Environment Variables
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"

# Production Environment
[env.production]
name = "inference-ui-api-production"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"

# Durable Objects - Commented out until RealtimeSession is deployed
# [[durable_objects.bindings]]
# name = "REALTIME"
# class_name = "RealtimeSession"
# script_name = "inference-ui-realtime"

# Build Configuration
[build]
command = "npm run build"

# Triggers for scheduled events - Commented out for initial deployment
# [[triggers.crons]]
# cron = "0 * * * *" # Every hour
