# Cloudflare Workers Configuration
# Account: FinHub

name = "inference-ui-api"
main = "src/index.ts"
compatibility_date = "2024-10-01"
workers_dev = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "inference-ui-db"
database_id = "4de74839-04b8-4b83-8550-578701999006"

# R2 Storage
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "inference-ui-assets"

# KV Namespace
[[kv_namespaces]]
binding = "KV"
id = "bfbe2757ae154da691a261a3af4fad85"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Workers AI
[ai]
binding = "AI"

# Environment Variables
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"

# Production Environment
[env.production]
name = "inference-ui-api-production"
workers_dev = false

[env.production.vars]
ENVIRONMENT = "production"

# Durable Objects - Commented out until RealtimeSession is deployed
# [[durable_objects.bindings]]
# name = "REALTIME"
# class_name = "RealtimeSession"
# script_name = "inference-ui-realtime"

# Build Configuration
[build]
command = "npm run build"

# Triggers for scheduled events - Commented out for initial deployment
# [[triggers.crons]]
# cron = "0 * * * *" # Every hour
