# Example Consumer Worker Configuration
# Shows how to configure service binding to Inference UI

name = "inference-ui-consumer-example"
account_id = "d9700a3fcc05a01f5d81670ebbae817d"
main = "index.ts"
compatibility_date = "2024-10-01"
workers_dev = true

# Service Binding to Inference UI
# This allows direct access without HTTP calls
[[services]]
binding = "INFERENCE_UI"
service = "inference-ui-api"
environment = "production"

# Optional: Smart Placement (recommended)
[placement]
mode = "smart"

[vars]
ENVIRONMENT = "development"
